// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.williamhaw.scalaxb.example

import scala.concurrent.{ Future, ExecutionContext }


/**
usage:
val obj = scalaxb.fromXML[com.williamhaw.scalaxb.example.Foo](node)
val document = scalaxb.toXML[com.williamhaw.scalaxb.example.Foo](obj, "foo", com.williamhaw.scalaxb.example.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  val defaultScope = scalaxb.toScope(None -> "http://www.example.com/IPO",
    Some("ipo") -> "http://www.example.com/IPO",
    Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val Comwilliamhawscalaxbexample_AddressableFormat: scalaxb.XMLFormat[com.williamhaw.scalaxb.example.Addressable] = new DefaultComwilliamhawscalaxbexample_AddressableFormat {}
  implicit lazy val Comwilliamhawscalaxbexample_AddressFormat: scalaxb.XMLFormat[com.williamhaw.scalaxb.example.Address] = new DefaultComwilliamhawscalaxbexample_AddressFormat {}
  implicit lazy val Comwilliamhawscalaxbexample_USAddressFormat: scalaxb.XMLFormat[com.williamhaw.scalaxb.example.USAddress] = new DefaultComwilliamhawscalaxbexample_USAddressFormat {}


  implicit val fromAnySchemaType: scala.xml.Elem => Option[scalaxb.DataRecord[Any]] = {elem =>
    import scalaxb.{Helper, DataRecord, fromXML}

    val ns = Helper.nullOrEmpty(elem.scope.getURI(elem.prefix))
    val key = Some(elem.label)
    val (xsns, xstype) = Helper.instanceType(elem)

    (key, ns) match {

      case _ => None
    }


  }

  trait DefaultComwilliamhawscalaxbexample_AddressableFormat extends scalaxb.XMLFormat[com.williamhaw.scalaxb.example.Addressable] {
    def reads(seq: scala.xml.NodeSeq, stack: List[scalaxb.ElemName]): Either[String, com.williamhaw.scalaxb.example.Addressable] = seq match {
      case node: scala.xml.Node =>     
        scalaxb.Helper.instanceType(node) match {
          case (Some("http://www.example.com/IPO"), Some("USAddress")) => Right(scalaxb.fromXML[com.williamhaw.scalaxb.example.USAddress](node, stack))
          case _ => Right(scalaxb.fromXML[com.williamhaw.scalaxb.example.Address](node, stack))
        }
      case _ => Left("reads failed: seq must be scala.xml.Node")  
    }
    
    def writes(__obj: com.williamhaw.scalaxb.example.Addressable, __namespace: Option[String], __elementLabel: Option[String],
        __scope: scala.xml.NamespaceBinding, __typeAttribute: Boolean): scala.xml.NodeSeq = __obj match {
      case x: com.williamhaw.scalaxb.example.USAddress => scalaxb.toXML[com.williamhaw.scalaxb.example.USAddress](x, __namespace, __elementLabel, __scope, true)
      case x: com.williamhaw.scalaxb.example.Address => scalaxb.toXML[com.williamhaw.scalaxb.example.Address](x, __namespace, __elementLabel, __scope, false)
    }
  }

  trait DefaultComwilliamhawscalaxbexample_AddressFormat extends scalaxb.ElemNameParser[com.williamhaw.scalaxb.example.Address] {
    val targetNamespace: Option[String] = Some("http://www.example.com/IPO")
    
    override def typeName: Option[String] = Some("Address")

    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[com.williamhaw.scalaxb.example.Address] =
      phrase((scalaxb.ElemName(Some("http://www.example.com/IPO"), "name")) ~ 
      (scalaxb.ElemName(Some("http://www.example.com/IPO"), "street")) ~ 
      (scalaxb.ElemName(Some("http://www.example.com/IPO"), "city")) ^^
      { case p1 ~ p2 ~ p3 =>
      com.williamhaw.scalaxb.example.Address(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: com.williamhaw.scalaxb.example.Address, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.name, Some("http://www.example.com/IPO"), Some("name"), __scope, false),
        scalaxb.toXML[String](__obj.street, Some("http://www.example.com/IPO"), Some("street"), __scope, false),
        scalaxb.toXML[String](__obj.city, Some("http://www.example.com/IPO"), Some("city"), __scope, false))

  }

  trait DefaultComwilliamhawscalaxbexample_USAddressFormat extends scalaxb.ElemNameParser[com.williamhaw.scalaxb.example.USAddress] {
    val targetNamespace: Option[String] = Some("http://www.example.com/IPO")
    
    override def typeName: Option[String] = Some("USAddress")

    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[com.williamhaw.scalaxb.example.USAddress] =
      phrase((scalaxb.ElemName(Some("http://www.example.com/IPO"), "name")) ~ 
      (scalaxb.ElemName(Some("http://www.example.com/IPO"), "street")) ~ 
      (scalaxb.ElemName(Some("http://www.example.com/IPO"), "city")) ~ 
      (scalaxb.ElemName(Some("http://www.example.com/IPO"), "state")) ~ 
      (scalaxb.ElemName(Some("http://www.example.com/IPO"), "zip")) ^^
      { case p1 ~ p2 ~ p3 ~ p4 ~ p5 =>
      com.williamhaw.scalaxb.example.USAddress(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p4, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[BigInt](p5, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: com.williamhaw.scalaxb.example.USAddress, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.name, Some("http://www.example.com/IPO"), Some("name"), __scope, false),
        scalaxb.toXML[String](__obj.street, Some("http://www.example.com/IPO"), Some("street"), __scope, false),
        scalaxb.toXML[String](__obj.city, Some("http://www.example.com/IPO"), Some("city"), __scope, false),
        scalaxb.toXML[String](__obj.state, Some("http://www.example.com/IPO"), Some("state"), __scope, false),
        scalaxb.toXML[BigInt](__obj.zip, Some("http://www.example.com/IPO"), Some("zip"), __scope, false))

  }


}

